version: '2.2'

services:
  db:
    image: mysql
    environment:
      MYSQL_USER: yoon
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: took
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - redis
    ports:
      - 3306:3306
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379